Tasks/task2 completed by Кирило Юрченко
UnoMomento12/altexsoft-lab-2020 pull request #3
Opened 2020-08-21 14:40 UTC by UnoMomento12

2020-08-25 20:51 UTC, serhii-shkodenko requested changes

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Controllers/CategoryController.cs
> +            return category;
Вы хотите просигнализировать пользователю, что операция по добавлению категории была успешно завершена. Например, этой цели может служить простое булевское значение, количество созданных записей в источнике данных, либо объект, возвращенный из источника данных. У Вас же возвращается то же, что и приходит.

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Controllers/CategoryController.cs
> +        //public void Add(Category category)
Если этот код более не нужен, удалите его.

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Controllers/IngredientController.cs
> +        //public Ingredient CreateAndGetIngredient(string ingName , string denomination)
Если этот код более не нужен, удалите его.

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Controllers/RecipeController.cs
> +        //public void AddSteps(Recipe recipe, List<string> steps)
Если этот код более не нужен, удалите его.

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Models/BaseModel.cs
> +        public BaseModel() { }
Зачем здесь дефолтный конструктор?

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Models/Category.cs
> +        public string ParentId { get; set; } = null;
Для типа стринг дефолтное значение и так `null`.

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Models/Category.cs
> +        public Category Parent { get; set; } = null;
Для типа стринг дефолтное значение и так `null`.

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Models/Ingredient.cs
> +        public string Denomination { get; set; } = "";
Зачем инициалазируете как пустую строку?

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Models/IngredientDetail.cs
> +        public IngredientDetail(Ingredient ing, double amount)
Обычно наличие подобного конструктора для инициализации всех свойств подразумевает, что у них не будет сеттеров. Рассмотрите целесобразность этого конструктора.

2020-08-25 20:51 UTC, serhii-shkodenko commented on task2/Navigator.cs
> +            _root = null;
Значения `_current` и `_root`и так null.

2020-08-26 17:33 UTC, serhii-shkodenko requested changes

2020-08-26 17:33 UTC, serhii-shkodenko commented on task2/Models/Category.cs
> +        public Category Parent { get; set; } = null;
Значение по умолчанию для рефренсных типов и так `null`. Не нужно это свойство таким образом инициалазировать.

2020-08-26 17:33 UTC, serhii-shkodenko commented on task2/Models/Category.cs
> +        public string ParentId { get; set; } = default;
Дефолтное значение для типа string `null`. Неясно, какую Вы цель преследуете.

2020-08-26 17:33 UTC, serhii-shkodenko commented on task2/Models/Recipe.cs
> +        public string Description { get; set; } = default;
Дефолтное значение для типа string `null`. Неясно, какую Вы цель преследуете.

2020-08-26 17:33 UTC, serhii-shkodenko commented on task2/Navigator.cs
> +                _current = retr as Category;
Вверху Вы уже знаете, что работает с категорией. Подумайте, как сократить количество кастов до одного.

2020-08-26 17:33 UTC, serhii-shkodenko commented on task2/Program.cs
> +                bool isNumber = Int32.TryParse(input, out option);
Воспользуйтесь псевдонимом для типа.

2020-08-26 17:33 UTC, serhii-shkodenko commented on task2/Program.cs
> +                while (Int32.TryParse(Console.ReadLine().Trim(), out categoryID) == false || navig.GetCategory(categoryID) == null)
Воспользуйтесь псевдонимом для типа. Общепринятым является использование именно псевдонимов, а не полных имен.

2020-08-26 17:33 UTC, serhii-shkodenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +            }
Зачем Вы храните данные? Я бы не усложнял так слой для доступа к данным, пусть он предоставляет данные по запросу. Задачу хранения можно возложить на другие слои.

2020-08-26 17:52 UTC, UnoMomento12 commented on task2/UnitsOfWork/UnitOfWork.cs
> +            }
Вот тут не понял, что имеется в виду? Данные у меня считываются из файла, эти методы восстанавливают(передают) референсы на объекты, которые категория должна содержать.

2020-08-26 17:58 UTC, UnoMomento12 commented on task2/UnitsOfWork/UnitOfWork.cs
> +            }
Если же это относилось к строке ниже где я опять информацию сохраняю, то я добавил её на такой кейс: есть 3 файла, и в файле с рецептами я удоляю один рецепт, в файле категории записан Id рецепта, при запуске программы, если при восстановлении референсов рецептов его не находит, id рецепта в списке рецептов категории удаляется, изменения сохраняются сразу( на тот случай если никаких действий в работающей программе совершено не будет).

2020-08-26 18:34 UTC, serhii-shkodenko requested changes

2020-08-26 18:34 UTC, serhii-shkodenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +            }
Вот эта логика наполнения рецептов ингридиентами и наполенения категории рецептами лучше разместить в методах соответствующих репозиториев. В общем случае конструкторы служат цели дать потребителю готовый для работы объект, логика с запросами здесь смотрится неуместной.

2020-08-26 18:34 UTC, serhii-shkodenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +    class UnitOfWork
В классической реализации паттерна UnitOfWork, этот класс должен реализовывать интерфейс IUnitOfWork.

2020-08-26 18:44 UTC, UnoMomento12 commented on task2/UnitsOfWork/UnitOfWork.cs
> +            }
Я думал об этом, но тогда получается, что бы восстановить ингредиенты в рецептах, прийдется передавать репозиторий игредиентов в репозиторий рецептов, а сам репозиторий рецептов в репозиторий категорий.

2020-08-26 19:14 UTC, serhii-shkodenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +            }
Да, скорее всего, Вы правы. Пусть реализация пока остается такой. Посмотрим, что скажет @alex-geraschenko. Но интерейс все-таки выделите. Он в дальнейшем Вам пригодится.

2020-08-27 13:25 UTC, alex-geraschenko requested changes

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Controllers/BaseController.cs
> +        protected IUnitOfWork _unitOfWork;
Именование с подчеркиванием вначале принято только для приватных полей. Для `protected` лучше использовать `PascalCase`

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Category.json
> +    "RecipeIds": [
Лучше сделать обратную зависимость. Не категория знает о рецептах, а рецепт знает, к какой категории он относится

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Controllers/CategoryController.cs
> +                category = item;
Плохая практика перезаписывать входные параметры

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Controllers/IController.cs
> +    {
Зачем нужен пустой интерфейс?

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Controllers/RecipeController.cs
> +                recipe = checker;
Плохая практика перезаписывать входные параметры

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Models/Category.cs
> +        public List<string> RecipeIds { get; set; } = new List<string>();
Лучше сделать обратную зависимость. Не категория знает о рецептах, а рецепт знает, к какой категории он относится

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Navigator.cs
> +            for( int b = _recipesStart; b < _subItems?.Count; b++)
Проверка на `null` тут не имеет смысла

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Program.cs
> +                    parsed = Double.TryParse(Console.ReadLine(), out amount);
Воспользуйтесь псевдонимом для типа.

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Program.cs
> +                    {
Зачем нужен пустой `else`?

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Program.cs
> +            return new Recipe() { Name = name, Description = description, Steps = steps };
Это ответсвтенность контроллера создавать рецепт

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Program.cs
> +                    answer = Console.ReadLine().Trim().ToLower();
Попробуйте `System.ConsoleKey`

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Program.cs
> +            if(choice == false)
Выражение можно упростить

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Repositories/Repository.cs
> +        protected List<T> _items;
Именование с подчеркиванием вначале принято только для приватных полей. Для `protected` лучше использовать PascalCase

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Repositories/IRepository.cs
> +        IEnumerable<T> Where(Func<T, bool> predicate);
Метод `Where` избыточен

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/Repositories/IRepository.cs
> +        T SingleOrDefault(Func<T, bool> predicate);
Метод `SingleOrDefault` избыточен

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +            if (_refDeleted) Categories.Save();
В конструкторе не должно быть логики сохранения. Это костыль

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +            if (_refDeleted) { DeleteDeadReferences(category, toDeleteInCategory); }
Нарушение принципа **Single Responsibility**

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +        private void RestoreIngredientsInRecipes()
Эту логику лучше вынести из `UnitOfWork` в контроллер

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +        private void RestoreRecipesInCategories()
Эту логику лучше вынести из `UnitOfWork` в контроллер

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +        private List<IngredientDetail> RestoreIngredients(Recipe recipe)
Эту логику лучше вынести из `UnitOfWork` в контроллер

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +        private Category RestoreParent(Category category)
Эту логику лучше вынести из `UnitOfWork` в контроллер

2020-08-27 13:25 UTC, alex-geraschenko commented on task2/UnitsOfWork/UnitOfWork.cs
> +        private List<Recipe> RestoreRecipesInCategory(Category category)
Эту логику лучше вынести из `UnitOfWork` в контроллер

2020-08-28 11:10 UTC, UnoMomento12 commented on task2/Repositories/IRepository.cs
> +        T SingleOrDefault(Func<T, bool> predicate);
@alex-geraschenko Я понять не могу, в чем избыточность этих двух методов? Я их использую 8 и 9 раз соответственно.

2020-08-28 15:30 UTC, alex-geraschenko commented on task2/Repositories/IRepository.cs
> +        T SingleOrDefault(Func<T, bool> predicate);
Они дублируют то, что есть в `System.Linq`.

2020-08-28 17:03 UTC, UnoMomento12 commented on task2/Repositories/IRepository.cs
> +        T SingleOrDefault(Func<T, bool> predicate);
@alex-geraschenko Ну так смысл в том, что бы в контроллерах вызывать этот метод через UnitOfWork.RepositoryName.SingleOrDefault(), а не UnitOfWork.RepositoryName.ItemsInRepository.SingleOrDefault() . 
Или я не правильно понимаю что именно дублируется?

2020-08-28 17:38 UTC, alex-geraschenko commented on task2/Repositories/IRepository.cs
> +        T SingleOrDefault(Func<T, bool> predicate);
Не `UnitOfWork.RepositoryName.ItemsInRepository.SingleOrDefault()`, а `UnitOfWork.RepositoryName.GetIAll().SingleOrDefault()`

Классическая реализация `Repository` включает в себя только 4 метода. Все остальное происходит или в сервисах или в контроллерах или при помощи шаблона `Specification`

2020-08-28 18:14 UTC, UnoMomento12 commented on task2/Repositories/IRepository.cs
> +        T SingleOrDefault(Func<T, bool> predicate);
Понятно, спасибо за разъяснение.

2020-08-31 09:50 UTC, alex-geraschenko requested changes

2020-08-31 09:50 UTC, alex-geraschenko commented on task2/EntityList;/Entities.cs
> +﻿using System.Collections.Generic;
Опечатка в пути к файлу

2020-08-31 09:59 UTC, UnoMomento12 commented on task2/EntityList;/Entities.cs
> +﻿using System.Collections.Generic;
@alex-geraschenko Исправил

2020-08-31 10:02 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-08-31 10:03 UTC, merged