Task4 by Кирило Юрченко.
UnoMomento12/altexsoft-lab-2020 pull request #5
Opened 2020-10-06 18:24 UTC by UnoMomento12

Все работает.

2020-10-07 06:38 UTC, serhii-shkodenko requested changes

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Cmd/HomeTask4.Cmd.csproj
> +    <TargetFramework>netcoreapp3.0</TargetFramework>
Можно испльзовать новейшую версию .NET Core 3.1. Именно для этой версии заявлен Long-term support.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Cmd/Navigator.cs
> +                //(await _unitOfWork.Repository.ListAsync<Recipe>()).Where(x => x.CategoryId == _current.Id).ToList().ForEach(x => _subItems.Add(x));
Удаляйте закомментированный код из PR.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +            Navigator navig = new Navigator(unitOfWork);
Создание экземпляра Navigator тоже можно возложить на IoC контейнер.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +                }
Код 
```
int option;
bool isNumber = int.TryParse(input, out option);
if (isNumber)
{
    await ProcessNumberAsync(option, navig);
}
```


можно сократить до:
```
if(int.TryParse(input, out var option))
{
    await ProcessNumberAsync(option, navig);
}
```

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +        public async Task<bool> TryCreateCategory(string categoryName, int? parentId)
Async забыли в имени метода.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +                return false;
Есть практика для таких случаев бросать исключения.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +                Console.WriteLine($"Category {item.Name} already exists!");
Для логирования лучше использовать `ILogger<T>`.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +                   //config.AddConsole();
Удаляйте закомментированный код.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/HomeTask4.Core.csproj
> +    <TargetFramework>netcoreapp3.0</TargetFramework>
Можно испльзовать новейшую версию .NET Core 3.1. Именно для этой версии заявлен Long-term support.

2020-10-07 06:38 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<UnitOfWork>();
Второй раз зарегистрировали UnitOfWork. Удалите.

2020-10-07 07:01 UTC, UnoMomento12 commented on task4/HomeTask4/HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<UnitOfWork>();
Без этого не работает, без понятия почему. @serhii-shkodenko

2020-10-07 07:04 UTC, UnoMomento12 commented on task4/HomeTask4/HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<UnitOfWork>();
![image](https://user-images.githubusercontent.com/50592775/95298268-7c5b5e00-0884-11eb-8e08-0d7dd46b6be8.png)

2020-10-07 07:05 UTC, UnoMomento12 commented on task4/HomeTask4/HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<UnitOfWork>();
Для юнита и всех контроллеров возвращает null.

2020-10-07 08:26 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Infrastructure/Extensions/ServiceCollectionExtensions.cs
> +            services.AddScoped<UnitOfWork>();
Это потому, что Вы обращаетесь к классу, а не к интерфейсу. У Вас:
`host.Services.GetRequiredService<UnitOfWork>();`
а должно быть
`host.Services.GetRequiredService<IUnitOfWork>();`

2020-10-08 11:39 UTC, serhii-shkodenko requested changes

2020-10-08 11:39 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/BaseController.cs
> +        protected ILogger _logger;
Раз `_logger` определили здесь, то и инициализировать его лучше здесь. Поправьте конструкторы классов-наследников. Обратитие внимание на имена. Протектед поля принято именовать в PascalCase.

2020-10-08 11:39 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +            } catch (Exception e)
Я бы здесь удалил этот try.. catch. Вы не знаете, какое исключение может придти, поэтому использзовали general catch block. Этого довольно спорная практика. Здесь есть общие [рекомендации, как отлавливать исключения](https://docs.microsoft.com/en-us/archive/msdn-magazine/2015/november/essential-net-csharp-exception-handling#wrapping-up).

2020-10-08 11:39 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return await TryCreateCategoryAsync(new Category { Name = categoryName, ParentId = parentId });
Избегайте применения констуркции `return await`. Верните просто Task<T>. Когда компилятор встречает конструкцию await, он разворачивает машину состояний. Однако здесь Вам не нужен результат и машина состояний развернется зря. Просмотрите весь код и поправьте.

2020-10-08 11:39 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +            return (await _unitOfWork.Repository.ListAsync<Category>()).FirstOrDefault(x => x.Id == parentId);
У Ваc же в репозитории есть GetByIdAsync(), зачем Вы достаете все категории, а потом в памяти фильтруете. Пусть Вам база данных сразу вернет одну категорию.

2020-10-08 11:39 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/RecipeController.cs
> +            var checker = (await _unitOfWork.Repository.ListAsync<Recipe>()).SingleOrDefault(x => string.Equals(x.Name, recipe.Name, StringComparison.OrdinalIgnoreCase) && x.CategoryId == recipe.Cate
Не надо проить БД дать вам все рецепты, а потом в апамяти их фильтровать. В репозитории должен быть метод, который возвращает один элемент по условию. Если его нет, добавьте. Все аналогичные места поправьте.

2020-10-08 13:14 UTC, UnoMomento12 commented
Добавил еще WhereAsync в репозиторий для дальнейшего использования в навигаторе.

2020-10-14 18:17 UTC, serhii-shkodenko requested changes
Вижу, что структура Ваших контроллеров подобна друг другу, поэтому поправьте их методы в соответствии с ревью к `CategoryController`.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +﻿using HomeTask4.SharedKernel.Interfaces;
Зачем Вам в четвертом задании тесты? Они должны быть в пятом.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +        public async Task CreateCategoryAsync(Category category)
Этот метод смотрит наружу и при этом Вы к нему обращаетесь лишь один раз из кода внутри класса. Его можно сделать либо приватным, либо вынести его код туда, где он используется. Скорее, эти два метода, которые вызываются под одному разу, являются частью одного метода.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +            catch (ArgumentNullException b)
Имя переменной можно сделать более описательным. В C# принято называть переменных для исключений в блоке `catch` как `ex`.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +                Logger.LogInformation(b.Message, b);
Имя переменной можно сделать более описательным. В C# принято называть переменных для исключений в блоке `catch` как `ex`.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +        public async Task<bool> TryCreateCategoryAsync(Category category)
Этот метод смотрит наружу и при этом Вы к нему обращаетесь лишь один раз из кода внутри класса. Его можно сделать либо приватным, либо вынести его код туда, где он используется.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +            bool result = await UnitOfWork.Repository.GetByIdAsync<Category>(category.Id) != null;
Выше Вы ловите `ArgumentNullException`, которую Вы бросаете, если категория равна `null`, а затем обращаетесь к свойству `Id` этой категории. Этим Вы провоцируете `NullReferenceException`. На `null` удобно проверять объект сразу, а не доверять это каким-то вспомагательным методам.

2020-10-14 21:40 UTC, UnoMomento12 commented
@serhii-shkodenko Спасибо большое за ревью. Перенес всю проверку полей в сам метод добавления сущности в контроллере, методы которые возвращают булевые флаги просто ловят экспепшены и логируют их. Так отпала необходимость ловить эксепшены в CMD.

2020-10-21 16:27 UTC, alex-geraschenko requested changes

2020-10-21 16:27 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +                Logger.LogInformation(nullException.Message);
В случае логирования иключений стоит применять `LogError`

2020-10-21 16:27 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/CategoryController.cs
> +                Logger.LogInformation(argumentException.Message);
В случае логирования иключений стоит применять `LogError`

2020-10-21 16:27 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/RecipeController.cs
> +                Logger.LogInformation(nullException.Message);
В случае логирования иключений стоит применять `LogError`

2020-10-21 16:27 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Core/Controllers/RecipeController.cs
> +                Logger.LogInformation(argumentException.Message);
В случае логирования иключений стоит применять `LogError`

2020-10-21 16:27 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Core/Navigator/Navigator.cs
> +    public class Navigator
Этот класс следует вынести в `CMD`, т.к. он зависит от консоли и выполняет работу, связвнную с UI. К тому же вместо `UnitOfWork` в нем следует применять контроллеры. А уже контроллеры отвечают за управление сущностями

2020-10-21 18:40 UTC, UnoMomento12 commented on task4/HomeTask4/HomeTask4.Core/Navigator/Navigator.cs
> +    public class Navigator
@alex-geraschenko А если я переделаю Navigator как контроллер, а методы вывода рецепта и дерева категорий перенесу как методы расширения в Program? Navigator станет независим от консоли и будет называться NavigatorController.

2020-10-27 16:52 UTC, alex-geraschenko requested changes

2020-10-27 16:52 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +                Console.WriteLine(a.Ingredient.Name + " : " + a.Amount + " " + a.Measure.Name);
Вместо конкатенации строк лучше использовать интерполяцию, как Вы и делаете в других местах кода. Пожалуйста, поменяйте по всему коду

2020-10-27 16:52 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +                PrintColored((i + 1) + ". " + recipe.Steps[i].Description, ConsoleColor.Cyan);
Вместо конкатенации строк лучше использовать интерполяцию, как Вы и делаете в других местах кода.

2020-10-27 16:52 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +                Console.WriteLine("    " + b + ". " + (navigator.SubItems[b] as Recipe)?.Name);
Вместо конкатенации строк лучше использовать интерполяцию, как Вы и делаете в других местах кода.

2020-10-27 16:52 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +                Console.WriteLine(i + ". " + (navigator.SubItems[i] as Category)?.Name);
Вместо конкатенации строк лучше использовать интерполяцию, как Вы и делаете в других местах кода.

2020-10-27 16:52 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Cmd/Program.cs
> +            if (option < 0) { await a.GoBack(); }
Лучше блоки кода внутри `if` переносить с новой строки даже если это одна строка
```
if (...)
{
    ...
}

2020-10-27 18:02 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-10-27 18:09 UTC, merged