Task5 by Кирило Юрченко
UnoMomento12/altexsoft-lab-2020 pull request #6
Opened 2020-10-08 10:41 UTC by UnoMomento12

2020-10-14 18:17 UTC, serhii-shkodenko requested changes
Пересмотрите ревью и поправьте во всех тестах, пожауйста, с учетом того, что было указано в ревью к четвертой таске.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +        private CategoryController _catCont;
Избегайте подобных сокращений. Для Вас они могут иметь смысл, а другому разработчнику на проекте понадобится время, чтобы понять, что же это за переменная. Например, нужно будет узнавать тип переменной, а если таких переменных будет много в коде, это выльется в значимое количество времени, которое можно было потратить более продуктивно.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            var repos = new Mock<IRepository>();
Наиболее приемлемым именем кажется `repositoryMock`. Приемлемым `repository`. Я когда прочитал имя переменной и не видел еще ее типа, подумал, что речь идет о коллекции репозиториев. Поправьте.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            _unitOfWork.Setup(u => u.Repository).Returns(repos.Object);
Для свойств есть специальный метод настройки `SetupGet()`. Используйте его.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            var excep = await Assert.ThrowsAsync<ArgumentException>(async () => await _catCont.TryCreateCategoryAsync("", 1));
Напишите имя переменной полностью.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +        public async Task TryCreateCategoryAsyncTest_Throws_Exception_On_Empty_Name()
В имени метода слово `Test` лучше убрать. `TryCreateCategoryAsync_...` этого достаточно.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            repos.Verify(repos => repos.GetByIdAsync<Category>(It.IsAny<int>()), Times.Never);
Фактически Ваш тест написан для метода `CreateCategoryAsync()`, потому что Вы не проверяете вызов логгера в случак возникновению исключения. Я бы в первую очередь проверял именно это.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +        public async Task TryCreateCategoryAsyncTest_Throws_Exception_On_Empty_Name()
Принято создавать отдельный тест на каждое исключение.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            var cat2 = new Category { Id = 4, Name = "First set", ParentId = null }; // overlapping category
Для вызова одного и того же метода с разными аргументами служат параметризированные тесты. Посмотрите в сторону атрибутов `[Theory]`, `[InlineData]`, `[MemberData]`.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            var result2 = await _catCont.TryCreateCategoryAsync(cat2);
Используйте параметризированные тесты.

2020-10-14 18:17 UTC, serhii-shkodenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            //Act + Assert
Здесь блоки Act и Assert явно разделены, это и следует указать с помощью комментариев.

2020-10-27 18:16 UTC, alex-geraschenko requested changes
1. Замечания из `CategoryControllerTests` применимы и ко всем остальным классам с тестами
2. Я уже писал в чате, что для пятого задания не нужно создавать отдельную папку и копировать в нее все приложение. Достаточно было добавить в существующий солюшен из 4 задания добавить проекто с тестами в новой гит ветке.

2020-10-27 18:16 UTC, alex-geraschenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            var mockRepository = new Mock<IRepository>();
Инициализацию `mockRepository`, а также `unitOfWorkMock.SetupGet(u => u.Repository).Returns(mockRepository.Object);` имеет смысл вынести в конструктор, т.к. это происходит во всех тестах

2020-10-27 18:16 UTC, alex-geraschenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +        [InlineData(3, "Soups", 1, false)]
Атрибу `InlineData` нужет для того, чтобы в один и тот же тест передавать разные параметры и проверять на ожидаемый результат. В Вашем случае постарайтесь объединить этот метод с предыдущим, тогда использование этого атрибута будет оправдано

2020-10-27 18:16 UTC, alex-geraschenko commented on task5/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +        public async Task CreateCategoryAsync_Doesnt_Throw_ArgumentNullException()
Из названия метода не понятно, почему не будет выброшено исключение. А также текст в `DisplayName` не соответствует имени теста. Лучше стараться писать понятные имена методов (тестов), тогда не будет необходимости в `DisplayName`

2020-10-30 13:24 UTC, serhii-shkodenko requested changes

2020-10-30 13:24 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            Category testedCategory = new Category { Id = id, Name = name, ParentId = parentId };
"testedCategory" переводится как "протестированная категория". Категория, которую нужно протестировать: "categoryToTest". Это важно, так как ксли Вы будете работать в международном проекте, кто-то другой может не понять, что Вы здесь делаете. Поправьте, пожалуйта, по всему проекту.

2020-10-30 13:24 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +                _mockRepository.Setup(r => r.AddAsync<Category>(It.IsAny<Category>())).Callback((Category some) => mockDB.Add(some));
'Some' это очень неинформативное имя. Можете как-то по-другому назвать?

2020-10-30 13:24 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +                _mockRepository.Setup(r => r.AddAsync<Category>(It.IsAny<Category>())).Callback((Category some) => mockDB.Add(some));
У Вас в метод в качестве аргумента приходит конкретная категория. Лучше проверить, что она была передана далее по стеку вызовов. Зачем это нужно? - Например, можно создать внутри Вашего тестируемого метода  категорию и ее уже передать в AddAsync(). При этом тест не упадет. Поправьте везде, пожалуйста: если Вы передаете в метод конкретный объект, проверьте, что он был передан дальше.

2020-10-30 13:24 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +        public async Task TryCreateCategoryAsync_Returns_Bool(int id, string name, int? parentId, bool isProblem, bool result)
Будет логичным переименовать параметр `result` в `expectedResult`, а фактический из `resultFlag` в `result` или `actualResult`.

2020-10-30 13:24 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +        public async Task TryCreateCategoryAsync_Throws_Exception_On_Empty_Name()
Когда Вы проверяете, что метод бросает исключение, в Вашем случае достаточным будет проверить, что нужное исключение действительно выброшено, его сообщение и вызов логера. Проверка того, что методы не вызываются (как и мок таких методов), мне кажется необснованным усложнением. Не могли бы Вы упростить этот тест и все ему подобные?

2020-10-31 11:39 UTC, UnoMomento12 commented
@serhii-shkodenko Убрал избыточные Verify методы из тестов которые выбрасывают ошибки, но оставил их в методах которые их не выбрасывают. Напишите пожалуйста, если и там нужно их бурать.

2020-11-03 18:43 UTC, serhii-shkodenko requested changes

2020-11-03 18:43 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            _mockRepository.Verify(r => r.GetByIdAsync<Category>(It.IsAny<int>()), Times.Never);
Я не вижу необходимости проверять, что методы не были вызваны. Эти проверки можно удалить.

2020-11-03 18:43 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +                _mockRepository.Setup(r => r.AddAsync<Category>(It.IsAny<Category>())).Callback((Category passedCategory) => {
Вы можете существенно сократить настройку ожидания. Проверьте, что метод `AddAsync()` вызывается с категорией, которая передана в метод контроллера: `Setup(r => r.AddAsync<Category>(categoryToTest)`. Тогда переменная `isPassedCategory ` будет не нужна, вызов `Callback()` тоже будет излишним. Не забутьте проверить Ваше ожидание с помощью `Verify(...)`. Поправьте во всех остальных контроллерах.

2020-11-03 18:43 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +                    isPassedCategory = passedCategory == categoryToTest;
Вы можете существенно сократить настройку ожидания. Проверьте, что метод `AddAsync()` вызывается с категорией, которая передана в метод контроллера: `Setup(r => r.AddAsync<Category>(categoryToTest)`. Тогда переменная `isPassedCategory ` будет не нужна, вызов `Callback()` тоже будет излишним. Не забутьте проверить Ваше ожидание с помощью `Verify(...)`. Поправьте во всех остальных контроллерах.

2020-11-03 18:43 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +                It.Is<Func<It.IsAnyType, Exception, string>>((v, t) => true)), Times.Never);
Эту проверку можно удалить.

2020-11-03 18:43 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +                It.Is<Func<It.IsAnyType, Exception, string>>((v, t) => true)), Times.Never);
Эту проверку можно удалить.

2020-11-03 18:43 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +                It.Is<Func<It.IsAnyType, Exception, string>>((v, t) => true)), Times.Never);
Эту проверку можно удалить.

2020-11-03 19:08 UTC, UnoMomento12 commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +                _mockRepository.Setup(r => r.AddAsync<Category>(It.IsAny<Category>())).Callback((Category passedCategory) => {
Почему-то вообще не выстрелило в голове что можно проверить на конкретном объекте.

2020-11-03 19:52 UTC, UnoMomento12 commented
@serhii-shkodenko Применил изменения, кроме удаления `Callback()` на методе `AddAsync()`. Если я удаляю коллбек на добавление сущности в список (псевдо-бд), то прийдется удалять коллбеки и на `FirstOrDefault()` и на `GetByIdAsync()` , и добавить что `GetByIdAsync()` просто возвращает false если в параметрах теста передается флаг, что есть проблема на стороне БД.

2020-11-03 21:36 UTC, serhii-shkodenko requested changes

2020-11-03 21:36 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            _mockRepository.Setup(r => r.FirstOrDefaultAsync<Category>(It.IsAny<Expression<Func<Category, bool>>>()))
Раз Вы настроили ожидание, проверьте его.

2020-11-03 21:36 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            _mockRepository.Setup(r => r.GetByIdAsync<Category>(id)).ReturnsAsync((int a) => mockDB.FirstOrDefault(x => x.Id == a));
Раз Вы настроили ожидание, проверьте его.

2020-11-03 21:36 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Verify(r => r.GetByIdAsync<Recipe>(It.IsAny<int>()), Times.Once);
Сюда можно передать `id` из входящих аргументов.

2020-11-03 21:36 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Setup(r => r.GetByIdAsync<Recipe>(It.IsAny<int>())).ReturnsAsync((int a) => mockDB.FirstOrDefault(x => x.Id == a));
Сюда можно передать `id` из входящих аргументов, как Вы сделали в CategoryControllerTests.

2020-11-03 21:36 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Setup(r => r.FirstOrDefaultAsync<Recipe>(It.IsAny<Expression<Func<Recipe, bool>>>()))
Раз Вы настроили ожидание, проверьте его.

2020-11-05 17:45 UTC, serhii-shkodenko commented
Отметьте, пожалуйста, кнопкой "Resolve conversastion" те предложения, которые Вы внедрили.

2020-11-05 18:23 UTC, serhii-shkodenko requested changes

2020-11-05 18:23 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            if (!isProblem)
А какую проблему Вы хотите с помощью этого флага заэмулировать?

2020-11-05 18:23 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            #region SameIngredientDetailArrange
Я бы не стал делать регион для одной строки, это излишне, на мой взгляд.

2020-11-05 18:23 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            //----------------------------------------------------------------------------------------------------------------------------------------//
Этот комментарий не добавляет ничего полезного, его можно удалить.

2020-11-05 18:23 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Verify(_mockRepository => _mockRepository.AddAsync<Measure>(It.IsAny<Measure>()), Times.Once);
Ранее в этом коде Вы использовали переменную с именем `r`. Я не вижу причин ее менять на `_mockRepository`, тем более вторая переменная имеет то же имя, что и замоканый Вами репозиторий, что может ввести в заблуждение того, кто читает Ваш код.

2020-11-05 18:23 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Verify(_mockRepository => _mockRepository.AddAsync<Measure>(It.IsAny<Measure>()), Times.Once);
Да, Вы здесь не можете настроить ожидание для конкретного объекта, потому что объект создается внтури метода контроллера, однако есть возможность проверить свойства этого объекта:
`It.Is<Measure>(entity => entity.Property1 == someValue1 && entity.Property1 == someValue2)`

2020-11-05 18:23 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Verify(_mockRepository => _mockRepository.AddAsync<Ingredient>(It.IsAny<Ingredient>()), Times.Once);
Да, Вы здесь не можете настроить ожидание для конкретного объекта, потому что объект создается внтури метода контроллера, однако есть возможность проверить свойства этого объекта:
`It.Is<Ingredient>(entity => entity.Property1 == someValue1 && entity.Property1 == someValue2)`

2020-11-05 18:23 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Verify(_mockRepository => _mockRepository.AddAsync<IngredientDetail>(It.IsAny<IngredientDetail>()), Times.Once);
Да, Вы здесь не можете настроить ожидание для конкретного объекта, потому что объект создается внтури метода контроллера, однако есть возможность проверить свойства этого объекта:
`It.Is<IngredientDetail>(entity => entity.Property1 == someValue1 && entity.Property1 == someValue2)`

2020-11-05 18:40 UTC, UnoMomento12 commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            if (!isProblem)
@serhii-shkodenko Проблема на стороне БД, допустим был вызов метода `AddAsync()`, но потом `FirstOrDefault()` не вернул этот элемент(лишб в таком случае вернется `false`). Хотя получается какой-то костыль, если такое никогда не произойдет, тот метод либо вернет true, либо перебросит ошибку.

2020-11-11 00:15 UTC, serhii-shkodenko requested changes

2020-11-11 00:15 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/CategoryControllerTests.cs
> +            //Arrange
Если блока //Arrange нет, то и комментарий можно удалить.

2020-11-11 00:15 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            if (!isProblem)
На данном уровне эмулировать подобное поведение является излишним. Кроме того, юнит тест предназначен для проверки корректности кода в Вашем методе, а он не содержит кода для которого нужно моделировать такое поведение. Удалите, пожалуйста.

2020-11-11 00:15 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Setup(r => r.AddAsync<Measure>(It.IsAny<Measure>()))
Здесь есть возможность настроить ожидание для параметра, воспользовавшись `It.Is<>()`, например `It.Is<Measure>(m => m.Name == "Some Name")`.

2020-11-11 00:15 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Setup(r => r.AddAsync<IngredientDetail>(It.IsAny<IngredientDetail>()))
Здесь есть возможность настроить ожидание для параметра, воспользовавшись` It.Is<>()`.

2020-11-11 00:15 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Setup(r => r.AddAsync<Ingredient>(It.IsAny<Ingredient>()))
Здесь есть возможность настроить ожидание для параметра, воспользовавшись `It.Is<>()`.

2020-11-11 00:15 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            IngredientDetail retrieved = mockIDDB.SingleOrDefault(x => x.RecipeId == recipeToTest.Id && x.IngredientId == mockIngredientDB.SingleOrDefault(x => x.Name == ingredientName)?.Id);
Переместите эту строку в блок `// Assert`, пожалуйста.

2020-11-11 00:15 UTC, serhii-shkodenko commented on task4/HomeTask4/HomeTask4.Core.Tests/ControllerTests/RecipeControllerTests.cs
> +            _mockRepository.Setup(r => r.UpdateAsync<IngredientDetail>(It.IsAny<IngredientDetail>()))
Здесь есть возможность настроить ожидание для параметра, воспользовавшись `It.Is<>()`.

2020-11-11 17:08 UTC, serhii-shkodenko approved these changes
У меня больше нет замечений. Выглядит достаточно хорошо. Как только @alex-geraschenko заапрувит, можно будет мержить.

2020-11-11 17:44 UTC, alex-geraschenko approved these changes
Хорошо, можно мержить

2020-11-11 17:51 UTC, merged