Tasks/task6 by Кирило Юрченко
UnoMomento12/altexsoft-lab-2020 pull request #7
Opened 2020-11-11 23:08 UTC by UnoMomento12

Основные функции выполнены.
Нужно дописать тесты к новым функциям эдита и делита.

2020-11-18 21:24 UTC, serhii-shkodenko commented
А зачем Вы добавили сюда тесты из пятого задания?

2020-11-18 21:36 UTC, UnoMomento12 commented
> А зачем Вы добавили сюда тесты из пятого задания?

я думал, что это продолжение одного проекта, в контроллерах были добавлены методы удаления и апдейта, я подумал нужно сделать соответствующие тесты.

2020-11-18 21:51 UTC, serhii-shkodenko commented
> > А зачем Вы добавили сюда тесты из пятого задания?
> 
> я думал, что это продолжение одного проекта, в контроллерах были добавлены методы удаления и апдейта, я подумал нужно сделать соответствующие тесты.

По-хорошему так и следует делать. Поскольку Вы изменили контроллер, Вы написали/изменили соответствующие тесты. Однако я вижу коммит "tests", которым закомичен проект с тестами из пятого задания. Этого не нужно было делать. Достаточно было вмержить мастер после комплита пятого задания, что Вы и сделали чуть позже.

2020-11-23 19:58 UTC, alex-geraschenko requested changes

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Infrastructure/Validators/EntityValidators.cs
> +    public class RecipeValidator : AbstractValidator<Recipe>
Разнесите классы по отдельным файлам

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Core/HomeTask4.Core.csproj
> +    <PackageReference Include="FluentValidation.AspNetCore" Version="9.3.0" />
А зачем Вам этот пакет в `Core` ?

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Edit.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Categories/Create.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Categories/Edit.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Ingredients/Create.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Ingredients/Edit.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Measures/Create.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Measures/Edit.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2020-11-23 19:58 UTC, alex-geraschenko commented on task4/HomeTask4/HomeTask4.Web/Pages/Recipes/Create.cshtml
> +    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
Пожалуйста, используйте `partial` для подключения `_ValidationScriptsPartial.cshtml`

2021-01-19 21:34 UTC, merged